#!/system/bin/sh

# ===========================================================================
#  Virtuous ROM Tools (rmk, chrisch)
#
#  $LastChangedDate: 2011-07-15 09:25:51 -0700 (Fri, 15 Jul 2011) $
# ===========================================================================

. /system/synergy/scripts/synergy-functions.sh

# Symlinking ebooks to /system/etc

if $TEST -d $SYNERGY_EBOOK_DIR ; then
  for EBOOKS in $($LS $SYNERGY_EBOOK_DIR/*.epub.stock) ; do
    EBOOKNAME=$($BASENAME $EBOOKS | $SED s/\.stock$//g)
    $LN -s $EBOOKS $SYSETC_DIR/$EBOOKNAME
  done;
fi
