#!/system/bin/sh.old
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
# 
###############################
#Starting FirstBoot Script
###############################
export LOG_FILE=/cache/dcboot.log;
export firstboot=`getprop dc.firstboot.active`;
busybox mount -o remount,rw -t auto /system;
busybox mount -o remount,rw -t auto /data;
busybox mount -o remount,rw -t auto /sdcard;
echo "[ ] Searching for FirstBoot script..." | tee -a $LOG_FILE;
if [ -e /data/firstboot.sh ];
then
	echo "[!] FirstBoot script found...executing." | tee -a $LOG_FILE;
	logwrapper /system/bin/sh.old /data/firstboot.sh;
	echo "[!] Removing FirstBoot Script." | tee -a $LOG_FILE;
	busybox rm -f /data/firstboot.sh;
fi;

