#!/sbin/sh
# Give us props if you use any of our stuff
# follow good open source etiquette
# thanks from Team Synergy
#
if [ ! -e  /data0/data.img ];
then
	/sbin/busybox dd if=/dev/mtd/mtd6ro of=/sdcard/data.img bs=4096 count=108000;
	rm -r /data0/*;
	rm -r /data0/*;
	/sbin/busybox mv /sdcard/data.img /data0/data.img;
	/sbin/mke2fs -T ext2 /data0/data.img -F;
	rm -r /data/*;
	rm -r /data/*;
fi;	