#!/system/bin/sh.old
#
############################
#Edited By: TrevE @ xda for damagedrom
#Create Log File
############################
SYNERGYROM=1;
export LOG_FILE=/cache/dcboot.log
if [ -e $LOG_FILE ]; then
  	rm $LOG_FILE;
fi;

echo "Starting DamageControl BootScript at:"  `date`  | tee -a $LOG_FILE;