#!/system/bin/sh
#
#File system speedups
#
busybox mount -o remount,ro,noatime,barrier=0,nobh /system
busybox mount -o remount,noatime,barrier=0,nobh /data
busybox mount -o remount,noatime,barrier=0,nobh /cache
sysctl -p
sync;
setprop cm.filesystem.ready 1;
setprop dc.filesystem.ready 1;
setprop oxygen.filesystem.ready 1;
